

services:
  postgres:
    image: postgres:16.6
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 7465
      POSTGRES_DB: uchi_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  bot:
    build:
      dockerfile: Dockerfile
      context: ./bot
    container_name: bot
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data: