services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: api
    ports:
      - "8080:8080"
    restart: unless-stopped

  bot:
    build:
      dockerfile: Dockerfile
      context: ./bot
    container_name: bot
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data: