

services:
  postgres:
    image: postgres:16.6
    container_name: postgres_ege
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 7465
      POSTGRES_DB: uchi_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: